### ISSUE TITLE
Voeg constraints toe die dubbele klant/evenement/gebruikers namen voorkomen

### ISSUE THREAD

**Issue by CodeLancasterX** [BarackOLlama/Festispec-App#111]
zorg dat de inegriteit van de database klopt.

**Comment by CodeLancasterX** [comment]
Begin transaction

**Constraint dubbele customer naam** - in de database.
Alter table dbo.Customers
Add Constraint UQ_CustomerName_Unique UNIQUE(Name)

Insert into dbo.Customers ( Name,Address,City,ZipCode,StartingDate,ChamberOfCommerceNumber,IsDeleted) values ('BermDingetje',null,null,null,null,null,0)

select * from dbo.Customers


**Constraint dubbele gebruikersnaam** - wachten op wijziging max chars @bartkoevoets 
Alter table dbo.Accounts
Add Constraint UQ_Username_Unique UNIQUE(Username)

insert into dbo.Accounts (Username, Password,Salt,IsAdmin, RoleId,IsDeleted) values('clancaster@gmail.com', null,null,0,null,0)

select * from dbo.Accounts


**Constraint dubbele evenement naam** wachten op wijziging max chars. @bartkoevoets 
Alter table dbo.Events 
Add Constraint UQ_EventName_Unique UNIQUE(Name)

insert into dbo.Events (Name, Address,City,Zipcode,CustomerId,EventDateId,IsDeleted) values ('Pinkpop',null,null,null,null,null,0)

Select * from dbo.Events


rollback transaction


**Test voor dubbele customer naam**
![image](https://user-images.githubusercontent.com/38426666/51767782-aaaffe80-20de-11e9-822f-6dcdd58b8f99.png)

**Comment by gharamorth** [comment]
Lijkt me ook handig voor velden zoals telefoonnummers en e-mail adressen right
