### ISSUE TITLE
Vragenlijst Invullen

### ISSUE THREAD

**Issue by Evert-Arends** [BarackOLlama/Festispec-App#12]
PUC nr: 12
BUC nr: 2
Trigger: Vragenlijst / antwoorden
Precondities: Evenement is bezig, Inspecteur kan inloggen, Inspecteur is gepland voor dit evenement.
Actor: Inspecteur
Stapsgewijze beschrijving (scenario):

- 12.1 De inspecteur logt in op de applicatie.
- 12.2 De inspecteur selecteert het evenement.
- 12.3 De inspecteur opent de vragenlijst.
- 12.4 De inspecteur voert de antwoorden in.
- 12.5 Het product slaat de antwoorden op.

Resultaat:
Vragenlijst is ingevuld en opgeslagen

**Comment by MarioZeldaDonkeyKong** [comment]
Kan deze issue weg?

**Comment by CodeLancasterX** [comment]
afgerond. getest door @MarioZeldaDonkeyKong & @yekcimickey
