### ISSUE TITLE
AvailableInspector fixen

### ISSUE THREAD

**Issue by DarjushKolahi** [BarackOLlama/Festispec-App#122]

**Comment by MarioZeldaDonkeyKong** [comment]
Bug / Issue

- Geen bevestigingsbericht bij aanmaak van inspectie
- Begin en eindtijd kan niet ingevuld worden
- Inspecteurs kan leeg blijven, geeft error bij + als je nieuwe inspectie aanmaakt https://i.imgur.com/1SdA6R2.png
- een nieuwe inspectie maakt een leeg veld aan in status https://i.imgur.com/wV8D26B.png 
- Afstand veld staat dubbel https://i.imgur.com/DePLZmK.png

**Comment by CodeLancasterX** [comment]
Lijkt nog buggy te zijn, mogelijk doordat er tegelijk getest wordt. 

de database constraints veroorzaken ook errors bij de available inspectors, dit gebeurde nadat ik een nieuwe inspectie aanmaakte en meteen een willekeurige inspcteur inplande en accepteerde.

Update: het lijkt alsof er een nieuwe customer wordt toegevoegd in de customer tabel zodra er een inspecteur is geselecteerd (met de "rechts" knop) en wordt opgeslagen (met de "accepteer" knop). 
Omdat er geen klant geselecteerd is, blijft dat dus op null staan en blijkbaar was er al een null in de customer tabel, vermoed ik.


![image](https://user-images.githubusercontent.com/38426666/52022182-07a11f80-24f8-11e9-8ade-b66ce578ffba.png)


![image](https://user-images.githubusercontent.com/38426666/52021943-218e3280-24f7-11e9-9eda-c8ecf21db97e.png)


.

![image](https://user-images.githubusercontent.com/38426666/52021819-c1978c00-24f6-11e9-979f-17b177e53ba9.png)

**Comment by CodeLancasterX** [comment]
bovengenoemde probleem lijkt niet meer aanwezig te zijn.

**Comment by DarjushKolahi** [comment]
@MarioZeldaDonkeyKong 

> Geen bevestigingsbericht bij aanmaak van inspectie

bevestigingsbericht toegevoegd

> Begin en eindtijd kan niet ingevuld worden

regex gefixt

> Inspecteurs kan leeg blijven, geeft error bij + als je nieuwe inspectie aanmaakt https://i.imgur.com/1SdA6R2.png

fixed

> een nieuwe inspectie maakt een leeg veld aan in status https://i.imgur.com/wV8D26B.png

fixed

> Afstand veld staat dubbel https://i.imgur.com/DePLZmK.png

fixed

**Comment by MarioZeldaDonkeyKong** [comment]
Priority

- Ik kan vaker dezelfde inspecteur kiezen als ik opnieuw de scherm opent https://i.imgur.com/TV4Lv9E.png 

- De afstand toont hij niet altijd (adressen bestaan).
