### ISSUE TITLE
klant window updates fix

### ISSUE THREAD

**Issue by CodeLancasterX** [BarackOLlama/Festispec-App#124]

**Comment by gharamorth** [comment]
Wat is het probleem hier exact?

**Comment by CodeLancasterX** [comment]
dit is opgelost zodra er niet meerdere schermen open gemaakt worden. het gaat namelijk om bijvoorbeeld het verwijderen updaten van een klant, terwijl je de evenement van die klant bijvoorbeeld bekijkt. hierdoor zie je bij die evenement niet de juiste gegevens bij een update.
