### ISSUE TITLE
Dubbelclick in eventmanagementview fix

### ISSUE THREAD

**Issue by CodeLancasterX** [BarackOLlama/Festispec-App#125]
Twee problemen in een: EventManagementView, dubbelklikken op een veld in de datagrid zorgt voor een exception, omdat die row niet zomaar gewijzigd kan worden. Ook kunnen er rows toegevoegd worden en dat is niet de bedoeling.
![image](https://user-images.githubusercontent.com/38426666/51853477-ad9e2f80-2328-11e9-915c-b55339e97dbd.png)

Suggesties / Verbeteringen
EventManagementView, regel 30

**Comment by gharamorth** [comment]
Zou nu opgelost moeten zijn.
