### ISSUE TITLE
Livecharts weergeven op rapportage

### ISSUE THREAD

**Issue by CodeLancasterX** [BarackOLlama/Festispec-App#131]

**Comment by MarioZeldaDonkeyKong** [comment]
Dit kan voor multiple choice vraag en schaalvraag https://i.imgur.com/9fNjIcx.png.

Livecharts: https://i.imgur.com/Ttvv0sB.png, https://i.imgur.com/7VCZrTD.png 

Handig zou zijn nog te testen op mogelijk fouten/missende zaken.

**Comment by CodeLancasterX** [comment]
Nieuwe issue voor aangemaakt ivm onleesbaarheid. 1 error nog opgetreden, momenteel nog lastig na te bootsen.
