### ISSUE TITLE
Inspectie status

### ISSUE THREAD

**Issue by MarioZeldaDonkeyKong** [BarackOLlama/Festispec-App#132]
Een inspectie moet een check doen dat het een vragenlijst bevat om de status ervan mogelijk op inplannen te zetten.

**Comment by gharamorth** [comment]
if (_context.QuestionnaireCrud.GetQuestionnaireByInspectionId(Inspection.Id) == null && Inspection.Status.StatusName == "Ingepland")
            {
                MessageBox.Show("De inspectie kan niet op \"Ingepland\" gezet worden omdat de inspectie geen vragenlijst heeft.");
                return false;
            }
