### ISSUE TITLE
Evenement Problemen

### ISSUE THREAD

**Issue by MarioZeldaDonkeyKong** [BarackOLlama/Festispec-App#138]
Bug / Issue

- Een evenement kan zonder een klant aangemaakt worden, wat ervoor zorgt dat lege klanten worden aangemaakt in de database (https://i.imgur.com/Kdv52q9.png). De lege klanten komen ook pas zichtbaar als je in klantenlijst een nieuwe klant toevoegt (https://i.imgur.com/QL6xZYc.png) en als je die lege klant probeert te bewerken krijg je een null reference (https://i.imgur.com/c1PHPtH.png).

- Evenement kan zonder start- en einddatum ingevuld worden.

Anders

- Je kunt bij evenement, als je deze specifieke postcode invoert: 4461VG accepteert hij dat niet. https://i.imgur.com/hpEIcKy.png

**Comment by gharamorth** [comment]
bugfixing 27_01_list branch:
-Klant is nu verplicht
-Startdatum is nu verplicht
-Einddatum is nu verplicht
-Postcode validatie is verbeterd; het laat nu een extra spatie tussen de cijfers en de letters toe- maar ik denk eerlijk gezegd dat je mogelijk een spatie voor of na je invoer had want anders moet het gewoon door de validatie komen. Kijk maar:
^[0-9]{4}[A-Z]{2}$ op regexr.com
