### ISSUE TITLE
Vragenlijst Problemen

### ISSUE THREAD

**Issue by MarioZeldaDonkeyKong** [BarackOLlama/Festispec-App#140]
- Wanneer ik een vragenlijst bewerk en op opslaan drukt krijgt ik deze error: https://i.imgur.com/vg8sLSx.png

- Een vragenlijst die ik verwijder kan nog gebruikt worden bij een inspectie voor het generen van een rapportage

- https://i.imgur.com/NKjSYMr.png opmerkingen en instructies is geen textwrap bij vragenlijst

**Comment by gharamorth** [comment]
Eerste probleem met het bewerken van vragenlijsten zou opgelost moeten zijn.
Textwrapping probleem is opgelost.

Een rapportage kan niet meer gegenereerd worden op een verwijderde vragenlijst; de _context query keek niet naar of de vragenlijst was verwijderd of niet.

btw: je kan meerdere afbeeldingen tegelijk uploaden bij imgur
