### ISSUE TITLE
verlof datum selectie fix

### ISSUE THREAD

**Issue by CodeLancasterX** [BarackOLlama/Festispec-App#141]
bij het aanvragen van een verlof kan bijvoorbeeld 1 januari 2001 geselecteerd worden. Het kan lang duren om die data toe te voegen in het rooster, als het werkelijk een jaartal zoals 2001 heeft zal de applicatie in breakmode gaan en daarnaast denk ik ook dat het onnodig is. 

![image](https://user-images.githubusercontent.com/38426666/52020722-b2aeda80-24f2-11e9-9e95-df7a24223d19.png)

een vorm van validatie toevoegen is misschien handig. (max aantal dagen verlof?)

**Comment by CodeLancasterX** [comment]
Fix in ScheduleManagementViewModel Below:

 private void NewScheduleItem()
        {
            if (IsInternetConnected())
            {
                if (StartingDate >= DateTime.Today)
                {
                    _Context.ScheduleItemCrud.AddScheduleItemsByDateRange(StartingDate, EndDate, SelectedInspector);
                    GetScheduleItems();
                }
                else
                {
                    MessageBox.Show("U probeerd een datum in het verleden te selecteren");
                }

            }
            else
                MessageBox.Show("U bent niet verbonden met het internet. Probeer het later opnieuw.");
        }

**Comment by bartkoevoets** [comment]
Added validation to not allow date ranges of more than 28 days at a time
