### ISSUE TITLE
Klanten Problemen

### ISSUE THREAD

**Issue by MarioZeldaDonkeyKong** [BarackOLlama/Festispec-App#142]
Priority,

~~- https://i.imgur.com/kb1bVRZ.png Ik krijg maar één klant te zien als ik een aantal toevoeg en dan het scherm sluit en opnieuw open. (Je moet de weergeven klant aanpassen om de rest terug te zien, https://i.imgur.com/EFKJXLm.png, **en het gebeurt eenmalig**)~~

Low Priority,

- Nadat je de contactpersoon scherm sluit onthoud hij de waardes die gevuld zijn als je het opnieuw opent https://i.imgur.com/uG0wCzF.png > https://i.imgur.com/e6hfJPm.png. 

- Bij contactpersoon als de naam/email te lang is past het niet meer op het scherm https://i.imgur.com/JFaZgBb.png.

~~- City (is Engels)~~ ~~https://i.imgur.com/JNvFHSp.png~~

**Comment by gharamorth** [comment]
Zijn al deze problemen nog relevant? Zo niet streep degene die niet meer relevant zijn met ~~ tekens (twee voor, twee achter)
