### ISSUE TITLE
Inspector Problemen

### ISSUE THREAD

**Issue by MarioZeldaDonkeyKong** [BarackOLlama/Festispec-App#143]
~~- https://i.imgur.com/CrIZOjX.png Huidige inspectie is geen, maar je ziet wel dat Curwen een heeft https://i.imgur.com/emakwUc.png.~~

~~- https://i.imgur.com/tG3G48D.png ik kan certificaat datum niet invoeren.~~

- Een inspecteur heeft geen account id bij aanmaak: https://i.imgur.com/tFio8Ty.png

**Comment by gharamorth** [comment]
Niet beloofd; niet doen?

**Comment by CodeLancasterX** [comment]
niet beloofd idd. als er een nieuwe account aangemaakt moet worden moet dit via de database. Dit gebeurd in de praktijk geloof ik ook.

**Comment by gharamorth** [comment]
*Niet direct via de database maar het kan via de seed en via een method in de LoginViewModel
