### ISSUE TITLE
Vragenlijst Probleem

### ISSUE THREAD

**Issue by MarioZeldaDonkeyKong** [BarackOLlama/Festispec-App#147]
- Wanneer ik een nieuwe vraag toevoeg update het vragenlijst beheer scherm niet voor "Aantal vragen" veld. (Pas als je hem opnieuw opstart) https://i.imgur.com/SpMYU07.png, zelfde als je ze verwijdert

- Inspectienummer wordt niet getoond, https://i.imgur.com/LJPb3DE.png.

**Comment by gharamorth** [comment]
Ik los dit probleem graag op maar het brengt met zich mee de risico dat er andere bugs worden geïntroduceerd. De functionaliteiten rondom de vragenlijsten zullen dan allemaal opnieuw getest worden.

De vraag is of dit risico en deze energie de moeite waard is sinds het Stijn waarschijnlijk niets zal uitmaken.
