### ISSUE TITLE
2e inspectie aanmaken fix

### ISSUE THREAD

**Issue by CodeLancasterX** [BarackOLlama/Festispec-App#149]
er kan eenmalig een nieuwe inspectie worden aangemaakt, zodra ik probeer een 2e aan te maken krijg ik een dbupdate error die aangeeft dat de unique constraint afgaat. Wanneer ik daarna in de database kijk zie ik dat er een rij met null waardes is toegevoegd, ondanks dat ik bij het aanmaken van beide inspecties wel verschillende waardes invul.

![image](https://user-images.githubusercontent.com/38426666/52169106-71593d80-2733-11e9-8ab2-b61483d7e872.png)

![image](https://user-images.githubusercontent.com/38426666/52169117-9ea5eb80-2733-11e9-8767-25f5a4d8f8fe.png)

**Comment by DarjushKolahi** [comment]
Is opgelost in de bugfixing branch @CodeLancasterX

**Comment by CodeLancasterX** [comment]
Fixed.
