### ISSUE TITLE
NULL objecten in database verwijderen

### ISSUE THREAD

**Issue by DarjushKolahi** [BarackOLlama/Festispec-App#154]
Null objecten werden aangemaakt bij bepaalde acties. zoals het maken van een nieuwe evenement. Er werd dan een customer aangemaakt met waardes die op null stonden, een soort van container. Die daarna werd gevuld met info, zodra de actie voldaan was.

**Comment by CodeLancasterX** [comment]
solved by @bartkoevoets .
