### ISSUE TITLE
AvailableInspector

### ISSUE THREAD

**Issue by DarjushKolahi** [BarackOLlama/Festispec-App#156]
Inspecteurs aan inspectie toevoegen, opslaan
Inspecteurs uit inspectie halen, opslaan
Inspecteurs aan inspectie toevoegen en uit inspectie halen, opslaan
Checken of relaties tussen Inspecteurs en Inspecties kloppen
Checken of scheduleitems goed aangemaakt en op IsDeleted 0 en 1 worden gezet

**Comment by MarioZeldaDonkeyKong** [comment]
Bug,

Als je iemand verlof geeft bijvoorbeeld tussen 6-2-2019 tot 8-2-2019 dan kan ik hem nog steeds selecteren bij een inspectie https://i.imgur.com/R4zQ8tD.png

Dit gebeurt er nu https://i.imgur.com/WG0IohY.png.

**Comment by CodeLancasterX** [comment]
fixed
