### ISSUE TITLE
PDF 

### ISSUE THREAD

**Issue by MarioZeldaDonkeyKong** [BarackOLlama/Festispec-App#158]
Als je webapp antwoorden invoert in de database dan vind hij ze niet in PDF generator.

EDIT: Local en azure, natuurlijk krijg je niet de antwoorden dan.

- PDFGenerator Check op of answerslist als die 0 is niet uitvoeren!
- ; naar | op basis van de seed

**Comment by CodeLancasterX** [comment]
fixed
