### ISSUE TITLE
Inspectie Zoeken

### ISSUE THREAD

**Issue by Evert-Arends** [BarackOLlama/Festispec-App#16]
PUC nr: 16
Trigger: Evenementnaam
Preconditie: Minstens één inspectie staat opgeslagen in de database
Actor: Operationele medewerker
Stapsgewijze beschrijving (scenario):
16.1 Operationele medewerker opent de lijst van de inspectie.
16.2 Operationele medewerker filtert de zoekkeuze.
16.3 Operationele medewerker zoekt inspecties op.

Resultaat:
Het systeem weergeeft de juiste inspectie

**Comment by MarioZeldaDonkeyKong** [comment]
Kan deze issue weg of was er nog een probleem?
