### ISSUE TITLE
Datepicker Issue

### ISSUE THREAD

**Issue by MarioZeldaDonkeyKong** [BarackOLlama/Festispec-App#162]
Leest bij alles behalve bij inspectie (dag / maand / jaar) de notatie als maand / dag / jaar. Daarom werkt datepicker niet voor deze gevallen.

**Comment by gharamorth** [comment]
Fixed in inspection_date_bugfix
Datepicker now binded on text rather than selectedate
Range limits(?) removed

**Comment by gharamorth** [comment]
<DatePicker Grid.Row="1" Grid.Column="1" Text="{Binding Inspection.InspectionDate.StartDate, Mode=TwoWay}" Width="350" HorizontalAlignment="Center" VerticalAlignment="Center" Margin="0,8"/>
