### ISSUE TITLE
Beschikbaarheid Inspecteurs Controleren

### ISSUE THREAD

**Issue by Evert-Arends** [BarackOLlama/Festispec-App#18]
PUC nr: 18
Trigger: Tijd
Preconditie: Er staan inspecteurs in de database
Actor: Medewerker
Stapsgewijze beschrijving (scenario):

- 18.1 Medewerker navigeert naar evenement
- 18.2 Medewerker klikt op beschikbaarheid inspecteurs controleren
- 18.3 Systeem controleerd beschikbaarheid op basis van datum en afstand die bij het evenement zijn aangegeven
- 18.4 Systeem geeft beschikbare inspecteurs terug gesorteerd op afstand van evenement

Resultaat:
Een lijst met beschikbare inspecteurs wordt getoont

**Comment by CodeLancasterX** [comment]
Dit geldt alleen voor de webapp :

We zijn een klein beetje afgeweken hiervan. De bedoeling was dat we een rooster zouden zien met de dagen dat iemand ingepland is.

functionaliteit is er. maar het is niet meer kloppend met de wireframe (dit zal waarschijnlijk bij andere functionaliteiten ook zo zijn)
