### ISSUE TITLE
Rapportage Verwerken (inspectie/klantgegevens weergeven)

### ISSUE THREAD

**Issue by Evert-Arends** [BarackOLlama/Festispec-App#22]
PUC nr: 22
Trigger: Inspectieresultaten
Preconditie: 
Actor: Operationele medewerker
Stapsgewijze beschrijving (scenario):

- 22.1 Operationele medewerker selecteert een evenement 
- 22.2 Operationele medewerker klikt op rapportage genereren 
- 22.3 Operationele medewerker stelt de opties in
- 22.4 Systeem genereert rapportage

Resultaat:
Het systeem heeft een rapportage gegenereerd

**Comment by MarioZeldaDonkeyKong** [comment]
Is dit niet bij inspecties gedaan? https://i.imgur.com/B1oUQmi.png,

**Comment by CodeLancasterX** [comment]
> Is dit niet bij inspecties gedaan? https://i.imgur.com/B1oUQmi.png,

omdat jullie aan verschillende delen van rapporten genereren werkten besloot ik deze issue te hernoemen en er een afzonderlijke issue van te maken. namelijk het weergeven van inspectie informatie (deze issue) en het weergeven van livecharts (andere issue)

**Comment by CodeLancasterX** [comment]
weergeeft juiste informatie. testen zullen hierop uitgevoerd worden en mochten er nieuwe problemen zijn dan zullen hier nieuwe issues voor aangemaakt worden.
