### ISSUE TITLE
Offerte aanmaken

### ISSUE THREAD

**Issue by Evert-Arends** [BarackOLlama/Festispec-App#26]
PUC nr: 26
Trigger: Tijd
Preconditie: De gegevens zijn bekend
Actor: Manager
Stapsgewijze beschrijving (scenario):

- 26.1 Manager selecteert klant
- 26.2 Manager klikt op offerte aanmaken
- 26.3 Systeem maakt offerte aan

Resultaat:
Offerte is aangemaakt

**Comment by CodeLancasterX** [comment]
customer is aware that quotation management will not be made.
