### ISSUE TITLE
Offerte wijzigen

### ISSUE THREAD

**Issue by Evert-Arends** [BarackOLlama/Festispec-App#27]
PUC nr: 27
Trigger: Wijziging
Preconditie: Er is een bestaande offerte
Actor: Manager
Stapsgewijze beschrijving (scenario):

- 27.1 Manager selecteert klant
- 27.2 Manager klikt op offerte wijzigen
- 27.3 Manager voert wijziging in
- 27.4 Systeem wijzigt offerte

Resultaat:
Offerte is gewijzigd

**Comment by CodeLancasterX** [comment]
customer is aware that quotation management will not be made.
