### ISSUE TITLE
Offerte zoeken

### ISSUE THREAD

**Issue by Evert-Arends** [BarackOLlama/Festispec-App#28]
PUC nr: 28
Trigger: Offertenummer
Preconditie: Er is een bestaande offerte
Actor: Manager
Stapsgewijze beschrijving (scenario):

- 28.1 Manager zoekt naar offerte
- 28.2 Systeem geeft offerte terug

Resultaat:
Offerte wordt weergeven

**Comment by CodeLancasterX** [comment]
customer is aware that quotation management will not be made.
