### ISSUE TITLE
Offline gegevens bewaren

### ISSUE THREAD

**Issue by bartkoevoets** [BarackOLlama/Festispec-App#38]
Zorgen dat de desktop app gegevens kan bewaren als er geen internetverbinding

**Comment by CodeLancasterX** [comment]
hoort dit niet bij de webapp als het om mobiele weergave gaat? @bartkoevoets

**Comment by CodeLancasterX** [comment]
functionaliteit zit in de development branche. Zal getest worden. Mochten er error optreden zal hiervan een nieuwe issue van gemaakt worden
