### ISSUE TITLE
Klantgegevens Zoeken

### ISSUE THREAD

**Issue by Evert-Arends** [BarackOLlama/Festispec-App#4]
PUC nr: 3
BUC nr: 2
Trigger: Klantnummer
Preconditie: Klant bestaat in het systeem
Actor: (Sales- of operationele medewerker)
Stapsgewijze beschrijving (scenario):
3.1 Medewerker voert (klantnummer of naam) in.
3.2 Systeem zoekt klant op.

Resultaat:
Klantgegevens zijn beschikbaar

**Comment by MarioZeldaDonkeyKong** [comment]
Deze issue kan weg?
